version: "3"
services:
  altar_app:
    image: trion/ng-cli:latest
    container_name: "altar_app"
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    # to create a new app in current directory
    # bash -c "ng new frontend-test --directory ./"
    ports:
      - 4200:4200
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --disableHostCheck"
  altar_test:
    image: trion/ng-cli-karma:latest
    container_name: "altar_test"
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    ports:
      - 9876:9876
    command: >
      bash -c "ng test"
